### ISSUE TITLE
Completar clase de subconsultas

### ISSUE THREAD

**Issue by Krax7** [devfmx/master-data-ai#52]
# Objetivos
- Separar el contenido del material base de la clase de Joins.
- Actualizar presentación
- Añadir ejercicios y ejemplos en los notebooks

# Material
1. [Slides](https://docs.google.com/presentation/d/1E-GFLPtfvnEbqmkoTiZdgb1xONxGt1CgHNJXZpiK2HE/edit?usp=sharing)
2. [Notebook teórico-práctico](https://colab.research.google.com/drive/1-1S9LL3offdoRajUsfG46QPJTNEXiBjP?usp=sharing)
3. [Notebook de challenge](https://colab.research.google.com/drive/17eIhdiCuTpC01G0tl1b0AeTtOdYmdbdD?usp=sharing)

# Cambios realizados:
- Añadir en el material base las slides de la 5 - 8 del material 1
- Revisión del notebook teórico-práctico
- Revisión del notebook de challenge

**Comment by Krax7** [comment]
Comentario con feedback

**Comment by Krax7** [comment]
@

> Comentario con feedback

Ah, estoy de acuerdo contigo

**Comment by ljanine** [comment]
Yo estoy de acuerdo con que se implemente este cambio

**Comment by juanin1114** [comment]
Yo tambien :)
